"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_purple)\
$os\
$hostname\
$username\
[ ](bg:color_purple)\
[](fg:prev_bg bg:color_yellow)\
$directory\
[](fg:prev_bg bg:color_aqua)\
$git_branch\
$git_status\
[](fg:prev_bg bg:color_blue)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
[](fg:prev_bg bg:color_bg3)\
${custom.python_status}\
[ ](fg:prev_bg)\
$line_break$character"""

right_format = """
$status\
$cmd_duration\
"""

palette = 'dracula'

[palettes.dracula]
color_aqua = '#8be9fd'
color_bg1 = '#282a36'
color_bg3 = '#44475a'
color_blue = '#6272a4'
color_fg0 = '#202020'
color_green = '#50fa7b'
color_orange = '#ffb86c'
color_purple = '#bd93f9'
color_red = '#ff5555'
color_yellow = '#f1fa8c'

[os]
disabled = false
style = "bg:color_purple fg:color_fg0"

[os.symbols]
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "�"
CentOS = ""
Debian = "󰣚"
EndeavourOS = ""
Fedora = "�"
Gentoo = "�"
Linux = "󰌽"
Macos = "󰀵"
Manjaro = ""
Mint = "�"
Pop = ""
Raspbian = "󰐿"
RedHatEnterprise = "󱄛"
Redhat = "󱄛"
SUSE = ""
Ubuntu = "󰕈"
Windows = "󰍲"

[username]
detect_env_vars = ["!TMUX_PANE"]
format = '[/$user]($style)'
show_always = true
style_root = "bg:color_purple fg:bold color_fg0"
style_user = "bg:color_purple fg:bold color_fg0"

[hostname]
detect_env_vars = ["!TMUX_PANE"]
format = '[ $hostname]($style)'
ssh_only = false
style = "bg:color_purple fg:bold color_fg0"

[hostname.aliases]
"Jacobs-MacBook-Air-M4" = "macbook-air"
"GK926344MW" = "macbook-pro"
"jtomlinson-workstation" = "workstation"

[directory]
format = "[ $path ]($style)"
style = "fg:color_fg0 bg:color_yellow"
truncation_length = 3
truncation_symbol = ""

[battery]
format = "$symbol"
unknown_symbol = '󰂄 '  # Workaround for https://github.com/starship/starship/issues/7136

[[battery.display]]
discharging_symbol = '󰁹 '
threshold = 100

[[battery.display]]
discharging_symbol = '󰂂 '
threshold = 90

[[battery.display]]
discharging_symbol = '󰂁 '
threshold = 80

[[battery.display]]
discharging_symbol = '󰂀 '
threshold = 70

[[battery.display]]
discharging_symbol = '󰁿 '
threshold = 60

[[battery.display]]
discharging_symbol = '󰁾 '
threshold = 50

[[battery.display]]
discharging_symbol = '󰁽 '
threshold = 40

[[battery.display]]
discharging_symbol = '󰁼 '
threshold = 30

[[battery.display]]
discharging_symbol = '󰁻 '
threshold = 20

[[battery.display]]
discharging_symbol = '󰂎 '
threshold = 10

[git_branch]
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'
style = "bg:color_aqua"
symbol = ""

[git_status]
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'
style = "bg:color_aqua"

[nodejs]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style = "bg:color_blue"
symbol = ""

[c]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style = "bg:color_blue"
symbol = " "

[cpp]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style = "bg:color_blue"
symbol = " "

[rust]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style = "bg:color_blue"
symbol = ""

[golang]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style = "bg:color_blue"
symbol = ""

[php]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style = "bg:color_blue"
symbol = ""

[java]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style = "bg:color_blue"
symbol = ""

[kotlin]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style = "bg:color_blue"
symbol = ""

[haskell]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style = "bg:color_blue"
symbol = ""

[python]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style = "bg:color_blue"
symbol = ""

[docker_context]
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'
style = "bg:color_bg3"
symbol = ""

[conda]
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'
style = "bg:color_bg3"

[pixi]
style = "bg:color_bg3"
#format = '[[ $symbol( $version)( $environment) ](fg:color_fg0 bg:color_bg3)]($style)'
format = '[[ ($environment) ](fg:color_fg0 bg:color_bg3)]($style)'
show_default_environment = false

[status]
disabled = false

[time]
disabled = false
format = '[  $time ]($style)'
style = "fg:color_bg3 bg:color_bg1"
time_format = "%R"

[line_break]
disabled = false

[character]
disabled = false
error_symbol = '[](bold fg:color_red)'
success_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'

[custom.python_status]
command = 'python_status'
detect_files = [
    ".python-version",
    "pyproject.toml",
    "requirements.txt",
    "tox.ini",
    "pixi.toml",
    "environment.yml",
    "uv.lock",
    "__init__.py",
]
detect_extensions = ["ipynb", "py"]
format = '[ $output]($style)'
style = "bg:color_bg3 fg:#83a598"
